### ISSUE TITLE
Indexed FASTA FIles

### ISSUE THREAD

**Issue by tshauck** [wheretrue/exon#417]
```[tasklist]
### Tasks
- [x] Support Passing region literal
- [x] Support passing local file
- [x] Support passing s3 file
- [x] Support coalecing byte ranges (if possible)
- [x] Update docs
- [ ] Add Test for GZIP and BGZIP Handling
```

**Comment by tshauck** [comment]
https://github.com/wheretrue/exon/pull/415 for local file

**Comment by tshauck** [comment]
#420 for passing s3 region file
